Repository WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team3, pull requests merged in 2022-11, with the labels that each got.

#6 All products
  frontend/src/App.css
  frontend/src/components/PosterMovie.jsx
  frontend/src/pages/AllProduct.jsx
Labels: Reveiw Done

#5 Findoutmore
  frontend/.eslintrc.json
  frontend/src/App.jsx
  frontend/src/assets/image/arbreperefils.jpeg
  frontend/src/assets/image/developementvert.png
  frontend/src/assets/image/developmentweb.png
  frontend/src/assets/image/panneausolaire.png
  frontend/src/assets/image/panneauvert.png
  frontend/src/assets/image/serveur.png
  frontend/src/assets/image/serveurvert.png
  frontend/src/components/Articles.jsx
  frontend/src/pages/NosValeurs.jsx
  frontend/src/pages/OurValues.jsx
Labels: Reveiw Done

#3 Navbar
  frontend/src/App.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/NavButton.jsx
  frontend/src/components/Subscribe.jsx
  frontend/src/pages/Account.jsx
Labels: Reveiw Done

#9 Hotfix POstermovie
  frontend/src/components/PosterMovie.jsx
Labels: Reveiw Done

#4 Movie card
  frontend/.eslintrc.json
  frontend/src/pages/OneProduct.css
  frontend/src/pages/OneProduct.jsx
Labels: Reveiw Done

#11 Navpage
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/picture/logo_vert_p2.png
  frontend/src/components/NavBar.jsx
  frontend/src/components/NavButton.jsx
Labels: Reveiw Done

#12 Backend allproduct
  backend/src/data/movies.js
  backend/src/router.js
Labels: Review Done

#15 ajout du complement toastify
  frontend/package-lock.json
  frontend/package.json
Labels: Review Done

#19 Modification export default
  frontend/src/services/films.js
Labels: Review Done

#18 Carouselforthreeimages
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Carrousel/Threefilm.jsx
  frontend/src/components/Footer.jsx
  frontend/src/pages/Home.jsx
Labels: Review Done

#23 Navpages
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/PosterMovie.jsx
  frontend/src/pages/AllProduct.jsx
Labels: Review Done

#25 Compteur
  frontend/src/components/Articles.jsx
  frontend/src/components/Compteur.jsx
  frontend/src/pages/OurValues.jsx
Labels: Change requested

#27 Mise à jour de OneProduct avec BDD
  frontend/src/App.jsx
  frontend/src/pages/AllProduct.jsx
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#24 All product liaison
  backend/src/router.js
  frontend/src/pages/AllProduct.jsx
Labels: Review Done

#29 Hotfix sur la allproduct + rename de movies en films pour garder la m…
  backend/src/router.js
  frontend/src/pages/AllProduct.jsx
Labels: Review Done

#30 finition du bouton compteur et ajout de l'icone d'arbre
  frontend/src/App.css
  frontend/src/assets/image/plant-d-arbre.png
  frontend/src/components/Compteur.jsx
Labels: Review Done

#31 Liaisoncarousel3films
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Carrousel/Threefilm.jsx
  frontend/src/pages/Home.jsx
Labels: Review Done

#32 Navpages
  frontend/src/components/NavBar.jsx
Labels: Review Done

#33 Refonte du carrousel 3 films pour éviter que le texte disparaisse en …
  frontend/index.html
  frontend/src/App.css
  frontend/src/components/Carrousel/Threefilm.jsx
Labels: Review Done

#34 Ajout carousel en ligne tendance
  frontend/index.html
  frontend/src/App.css
  frontend/src/components/Carrousel/Multiplefilm.jsx
  frontend/src/components/Carrousel/Scriptcarouselenligne.js
  frontend/src/components/Carrousel/multiplefilmmap.jsx
  frontend/src/pages/Home.jsx
Labels: Review Done

#35 Creation de la page account
  frontend/src/pages/Account.css
  frontend/src/pages/Account.jsx
Labels: Review Done

#36 Hotfix OneProduct
  frontend/index.html
  frontend/src/App.css
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#38 Allproducts filtres
  frontend/src/App.css
  frontend/src/assets/picture/fleche.menu.png
  frontend/src/assets/picture/user_1.png
  frontend/src/pages/AllProduct.jsx
Labels: Review Done

#37 ajout de la fonction routeur sur la nav bar
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/PosterMovie.jsx
  frontend/src/pages/AllProduct.jsx
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#39 Connexback
  frontend/index.html
  frontend/src/components/Carrousel/Multiplefilm.jsx
  frontend/src/components/Carrousel/multiplefilmmap.jsx
Labels: Review Done

#41 hotfix suppression des setPage sur threefilm
  frontend/src/components/Carrousel/Threefilm.jsx
Labels: Review Done

#43 modification lien icone compteur dans le composant compteur
  frontend/src/components/Articles.jsx
  frontend/src/components/Compteur.jsx
Labels: Review Done

#44 hotfix sur le nombre affiches par colonne + suppression de la page on…
  frontend/src/components/PosterMovie.jsx
  frontend/src/pages/AllProduct.jsx
  frontend/src/pages/OneProduct.css
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#45 ajout demi photo sur caroussel. Mis en anglais et centrage reserved s…
  frontend/src/components/Carrousel/Scriptcarouselenligne.js
  frontend/src/components/Footer.jsx
Labels: Review Done

#46 Hotfix pour centrer l ecriture de la navbar
  frontend/src/components/NavBar.jsx
Labels: Review Done

#49 hotfixe compteur et ajout page css compteur
  frontend/src/App.css
  frontend/src/components/Compteur.jsx
  frontend/src/pages/OurValues.css
  frontend/src/pages/OurValues.jsx
Labels: Review Done

#50 Mise en place envoie d'un email depuis la page account
  frontend/index.html
  frontend/package.json
  frontend/src/pages/Account.jsx
Labels: Review Done

#51 Hotfixoneproduct
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#52 Connection de threefilm à la db
  backend/src/db.js
  backend/src/router.js
  frontend/src/components/Carrousel/Threefilm.jsx
Labels: Review Done

#54 create seconde carousel in ligne and delete herringbone
  frontend/index.html
  frontend/src/components/Carrousel/Multiplefilm.jsx
  frontend/src/components/Carrousel/Multiplefilm2.jsx
  frontend/src/components/Carrousel/Scriptcarouselenligne.js
  frontend/src/components/Carrousel/multiplefilmmap.jsx
  frontend/src/pages/Home.jsx
Labels: Review Done

#55 Nav footer
  frontend/src/components/FooterNavButton.jsx
  frontend/src/pages/AllProduct.jsx
Labels: Review Done

#58 Ajout de la navigation au SignIn et SignUp + choix abonnement uni…
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/pages/Account.jsx
Labels: Review Done

#56 Add carousel in page oneproduct
  frontend/src/components/Carrousel/Multiplefilm2.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#62 Add loading button
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#60 Nav search
  frontend/src/components/NavBar.jsx
  frontend/src/pages/AllProduct.jsx
  frontend/src/pages/OneProduct.jsx
Labels: Change requested

#61 traduction text et modif css caroussel trois films
  frontend/src/App.css
  frontend/src/components/Carrousel/Threefilm.jsx
Labels: Change requested

#63 Hotfix allprodcuct
  frontend/src/pages/AllProduct.jsx
Labels: Review Done

#64 Ajout du CSS pour les liens
  frontend/src/App.css
Labels: Review Done

#57 ajout sio sur toutes les pages
  frontend/index.html
  frontend/src/pages/Account.jsx
  frontend/src/pages/AllProduct.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/OneProduct.jsx
  frontend/src/pages/OurValues.jsx
  frontend/src/services/Meta.js
Labels: Review Done

#66 hotfix home et ajout desc sur les alt de threefilms
  frontend/src/components/Carrousel/Threefilm.jsx
  frontend/src/pages/Home.jsx
Labels: Review Done

#59 Favoris
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#68 Hotfix navbar
  frontend/src/App.css
  frontend/src/components/Footer.jsx
  frontend/src/components/NavBar.jsx
Labels: Review Done

#67 hotfix de bugs
  frontend/src/components/Carrousel/Multiplefilm.jsx
  frontend/src/components/Carrousel/Multiplefilm2.jsx
  frontend/src/pages/Home.jsx
Labels: Review Done

#71 Boutoncategory
  backend/src/router.js
  frontend/src/components/Carrousel/BoutonCategory.css
  frontend/src/components/Carrousel/BoutonCategory.jsx
  frontend/src/components/Carrousel/Scriptcarouselenligne.js
  frontend/src/pages/Home.jsx
Labels: Review Done

#70 Modification des imports des images et CSS button
  backend/src/router.js
  frontend/src/App.jsx
  frontend/src/components/Carrousel/FilmAction.jsx
  frontend/src/components/Carrousel/Multiplefilm2.jsx
  frontend/src/components/Carrousel/Multiplefilm3.jsx
  frontend/src/components/Carrousel/Multiplefilm4.jsx
  frontend/src/components/Carrousel/Scriptcarouselenligne.js
  frontend/src/components/NavBar.jsx
  frontend/src/pages/Account.jsx
  frontend/src/pages/AllProduct.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#72 hotfix
  backend/src/router.js
  frontend/src/components/Carrousel/Multiplefilm3.jsx
  frontend/src/components/Carrousel/Multiplefilm4.jsx
  frontend/src/pages/Home.jsx
Labels: Review Done
